name: coda19-exp
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip
  - pip:
    - transformers==4.28.1
    - accelerate==0.18.0
    - typer==0.7.0
    - protobuf==3.20.0
    - comet-ml
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - sentencepiece
    - openai
    - gpustat
    - datasets==2.5.1
    - evaluate
    - numpyencoder
    - aiohttp
variables:
  COMET_API_KEY: ooooooooooooooooooooooooooo
  OPENAI_API_KEY: sk-oooooooooooooooooooooooooooooooooooooooo
  PYTHONUSERBASE: intentionally-disabled
